/* 
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
let fib_sequence = [1,2];
let total = 2 

let index = 2

while (index <= 4000000){
    let value = fib_sequence[index-1] + fib_sequence[index-2]

    if (value > 4000000){
        break
    }
    fib_sequence.push(value)

    if( value % 2 == 0){
        total += value
    }
    

    index++
}

console.log(total)